from __future__ import annotations

import shutil
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "data" / "generated_snapshot"
TABLE_DIR = ROOT / "outputs" / "tables"
REPORT_DIR = ROOT / "reports"
SNAPSHOT.mkdir(parents=True, exist_ok=True)

FILES_TO_COPY = [
    TABLE_DIR / "customer_segments.csv",
    TABLE_DIR / "campaign_events_with_segments.csv",
    TABLE_DIR / "segment_profile_summary.csv",
    TABLE_DIR / "offer_uplift_by_segment.csv",
    TABLE_DIR / "segment_offer_recommendations.csv",
    TABLE_DIR / "executive_metrics.csv",
    TABLE_DIR / "cluster_selection_scores.csv",
]


def main() -> None:
    rows = []
    for src in FILES_TO_COPY:
        if not src.exists():
            raise FileNotFoundError(f"Missing generated table: {src}")
        dst = SNAPSHOT / src.name
        shutil.copy2(src, dst)
        rows.append({
            "path": str(dst.relative_to(ROOT)),
            "rows": len(pd.read_csv(dst)),
            "size_bytes": dst.stat().st_size,
        })

    sql_dir = TABLE_DIR / "sql_checks"
    if sql_dir.exists():
        out_sql = SNAPSHOT / "sql_checks"
        out_sql.mkdir(exist_ok=True)
        for src in sorted(sql_dir.glob("*.csv")):
            dst = out_sql / src.name
            shutil.copy2(src, dst)
            rows.append({
                "path": str(dst.relative_to(ROOT)),
                "rows": len(pd.read_csv(dst)),
                "size_bytes": dst.stat().st_size,
            })

    manifest = pd.DataFrame(rows).sort_values("path")
    manifest.to_csv(SNAPSHOT / "snapshot_manifest.csv", index=False)

    readme = """# Generated snapshot

This folder stores one generated run from the synthetic UKPI analytics demo.

It is checked into the repository so the project is not only visible through GitHub Actions artifacts. The data here are still synthetic. They are not Vanguard data and not real customer data.

The snapshot is regenerated by:

```bash
python ukpi_analytics_demo.py
python scripts/run_sql_checks.py
python scripts/export_generated_snapshot.py
```

The source of truth remains the code. This folder is a reviewable frozen output from one run.
"""
    (SNAPSHOT / "README.md").write_text(readme, encoding="utf-8")
    print(f"Wrote generated snapshot to {SNAPSHOT}")
    print(manifest.to_string(index=False))


if __name__ == "__main__":
    main()
