from __future__ import annotations

import shutil
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "data" / "generated_snapshot"
TABLE_DIR = ROOT / "outputs" / "tables"

REQUIRED_FILES = [
    TABLE_DIR / "customer_segments.csv",
    TABLE_DIR / "campaign_events_with_segments.csv",
    TABLE_DIR / "segment_profile_summary.csv",
    TABLE_DIR / "offer_uplift_by_segment.csv",
    TABLE_DIR / "segment_offer_recommendations.csv",
    TABLE_DIR / "offer_uplift_with_uncertainty.csv",
    TABLE_DIR / "data_quality_summary.csv",
]

OPTIONAL_FILES = [
    TABLE_DIR / "executive_metrics.csv",
    TABLE_DIR / "cluster_selection_scores.csv",
]


def copy_csv(src: Path, dst: Path) -> dict[str, object]:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return {
        "path": str(dst.relative_to(ROOT)),
        "rows": len(pd.read_csv(dst)),
        "size_bytes": dst.stat().st_size,
    }


def main() -> None:
    if SNAPSHOT.exists():
        shutil.rmtree(SNAPSHOT)
    SNAPSHOT.mkdir(parents=True, exist_ok=True)

    rows = []
    for src in REQUIRED_FILES:
        if not src.exists():
            raise FileNotFoundError(
                f"Missing required generated table: {src}. "
                "Run the demo, evidence, and SQL scripts first."
            )
        rows.append(copy_csv(src, SNAPSHOT / src.name))

    for src in OPTIONAL_FILES:
        if src.exists():
            rows.append(copy_csv(src, SNAPSHOT / src.name))

    sql_dir = TABLE_DIR / "sql_checks"
    if not sql_dir.exists():
        raise FileNotFoundError(
            f"Missing SQL output directory: {sql_dir}. "
            "Run python scripts/run_sql_checks.py first."
        )

    out_sql = SNAPSHOT / "sql_checks"
    for src in sorted(sql_dir.glob("*.csv")):
        rows.append(copy_csv(src, out_sql / src.name))

    manifest = pd.DataFrame(rows).sort_values("path")
    manifest.to_csv(SNAPSHOT / "snapshot_manifest.csv", index=False)

    readme = """# Generated snapshot

This folder stores one generated run from the synthetic UKPI analytics demo.

It is checked into the repository so the project is not only visible through GitHub Actions artifacts. The data here are still synthetic. They are not Vanguard data and not real customer data.

The snapshot is regenerated by:

```bash
python ukpi_analytics_demo.py
python scripts/build_evidence_layer.py
python scripts/run_sql_checks.py
python scripts/export_generated_snapshot.py
python scripts/build_guided_dashboard.py
```

The source of truth remains the code. This folder is a reviewable frozen output from one run, including uncertainty estimates, data-quality checks, and SQL results.
"""
    (SNAPSHOT / "README.md").write_text(readme, encoding="utf-8")
    print(f"Wrote generated snapshot to {SNAPSHOT}")
    print(manifest.to_string(index=False))


if __name__ == "__main__":
    main()
